### ISSUE TITLE
Scroll naves

### ISSUE THREAD

**Issue by marlonassuncao** [walterdis/spacecrypto-bot#2]
Cara primeiramente obg!!! Só observei 1 problema. Ele não faz scroll na lista de naves e se a primeira estiver sem energia, bloqueia que as próximas que possam ter energia sejam colocadas em trabalho. Existe uma possibilidade de ter um scroll automático até chegar em uma nave com fight habilitado?

**Comment by walterdis** [comment]
Opa cara, na realidade ele faz, porém o jogo parece que complica a detecção de imagens. (na minha VM deu esse mesmo problema)

Tenta fazer o seguinte:
Tirar novamente uma foto do botão de "fight" disponível.

Se não resolver, vais ter que mudar a "taxa de precisão" no bot (depois vou melhorar isso).
Abre o arquivo shipselect.py

Nas linhas 159, 185, 242 e 286, tem esse método: helper.getImagePositions('ship-fight-button.png', 0.9, screen)

O segundo parâmetro é o que vc vai mexer (coloca igual para todos)
Na minha VM eu botei 0.97 e funcionou. (testa entre 0.97 e 0.99 para ver se resolve)

O valor vai de 0 a 1. Quanto maior o número, maior é a precisão que a imagem precisa ter com a que está sendo comparada

Logo mais quero ver se atualizo e coloco essa verificação dentro de um método apenas para facilitar o ajuste.

Obs: Não esquece que o browser tem que estar em 50% do zoom

**Comment by marlonassuncao** [comment]
Cara muito obrigado. Deu certo! É possível diminuir a distância de scroll que ele faz? Porque as vezes passa algumas que estão ativas e ele sobe muito rápido, é possível diminuir esse offset?

**Comment by walterdis** [comment]
> min

Claro! (e olha que já diminui bastante)
No mesmo arquivo, lá pela linha 269  +-, tem o pyautogui.dragRel(0, -200, duration=1, button='left')
Esse -200 é o quanto ele vai rolar, ai ajusta para o valor que achares melhor ;)

**Comment by marlonassuncao** [comment]
Muito obrigado! Agora voa!!!! hahahaha
