### ISSUE TITLE
fix: scroll não funciona ao selecionar naves.

### ISSUE THREAD

**Issue by salmomascarenhas** [walterdis/spacecrypto-bot#4]
Ao selecionar o filtro de max armor e a primeira não está pronta para batalha, o click não ocorre na nave abaixo (que está pronta) como deveria ser.

**Comment by salmomascarenhas** [comment]
Estou estudando o código para tentar um PR.

**Comment by walterdis** [comment]
Opa, isso dai é algo estranho com o jogo que não detecta a imagem mais abaixo (e se faço detectar ela, ele acaba não detectando as outras).
Se fizer um scroll de leve pra cima, ele passa a detectar.
Quando diminuo o threshold, ai acaba clicando nos botões de fight desabilitados.
Ainda estou tentando encontrar uma boa solução para isso (tipo ler o background com a cor vermelha).

**Comment by salmomascarenhas** [comment]
> Opa, isso dai é algo estranho com o jogo que não detecta a imagem mais abaixo (e se faço detectar ela, ele acaba não detectando as outras). Se fizer um scroll de leve pra cima, ele passa a detectar. Quando diminuo o threshold, ai acaba clicando nos botões de fight desabilitados. Ainda estou tentando encontrar uma boa solução para isso (tipo ler o background com a cor vermelha).

Entendi! 
Acho inclusive que o erro de inatividade (https://github.com/walterdis/spacecrypto-bot/issues/5) começa justamente por conta desse problema descrito nessa issue.

Tipo... como não consegue clicar em outras opções abaixo sem ser a primeira (desabilitada), ele cai em inatividade.

Irei seguir estudando o código.
