### ISSUE TITLE
bot sem funcionar

### ISSUE THREAD

**Issue by salmomascarenhas** [walterdis/spacecrypto-bot#6]
Alguém sabe dizer se teve att visual no spacecrypto ? O bot estava funcionando a mil na madrugada e pela manhã, mas agora, durante a noite fui colocar, não detecta mais as imagens e não se comporta como o esperado.

Penso que pode ser alguma atualização de resolução/qualidade_de_imagem do SpaceCrypto.

**Comment by walterdis** [comment]
> Alguém sabe dizer se teve att visual no spacecrypto ? O bot estava funcionando a mil na madrugada e pela manhã, mas agora, durante a noite fui colocar, não detecta mais as imagens e não se comporta como o esperado.
> 
> Penso que pode ser alguma atualização de resolução/qualidade_de_imagem do SpaceCrypto.

Opa ;)
O zoom do teu browser no jogo está em 50%?
As vezes podes ter restaurado ele sem querer.
Aqui no momento está funcionando o bot.
Se já estiver em 50%, tenta tirar as fotos de algumas imagens para ver se arruma (nem se autenticar ele está autenticando?)

**Comment by salmomascarenhas** [comment]
> > Alguém sabe dizer se teve att visual no spacecrypto ? O bot estava funcionando a mil na madrugada e pela manhã, mas agora, durante a noite fui colocar, não detecta mais as imagens e não se comporta como o esperado.
> > Penso que pode ser alguma atualização de resolução/qualidade_de_imagem do SpaceCrypto.
> 
> Opa ;) O zoom do teu browser no jogo está em 50%? As vezes podes ter restaurado ele sem querer. Aqui no momento está funcionando o bot. Se já estiver em 50%, tenta tirar as fotos de algumas imagens para ver se arruma (nem se autenticar ele está autenticando?)

Estava usando todo esse tempo em 50% e estava funfando (verifiquei e está sim em 50%). Irei tentar tirar as fotos novamente!

**Comment by salmomascarenhas** [comment]
Realmente, pude resolver tirando novos prints.
Obrigado!
